#!/bin/sh
set -e

if [ ! -d oneline ] 
then
  echo "Run me from the finitecurve.com checkout" >&2
  exit 1
fi

(
  cd oneline
  CXXFLAGS='-O2 -DNDEBUG' emmake make oneline.js && cp oneline.js oneline.wasm ../public
)

npm install
npm run build
